[package]
name = "base"
version = "0.1.0"
authors = ["z5661068@gmail.com <z5661068@gmail.com>", "The Chromium OS Authors"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_model = { path = "../data_model" }
libc = "*"